BloggingPlatform/BloggingPlatform/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
    
]

BloggingPlatform/blogs/urls.py
from django.urls import path

from .views import *

urlpatterns=[
    path('',home,name='home'),
    path('register/',register,name='register'),
    path('login/',user_login,name='login'),
    path('logout/',user_logout,name='logout'),
    path('profile/',profile,name='profile'),
    path('create-post/',createpost,name='create_post'),
    path('edit/<int:post_id>/', edit_blog_post, name='edit_blog_post'),
    path('delete/<int:post_id>/', delete_blog_post, name='delete_blog_post'),
    path('post-details/<int:post_id>',viewpost,name='post_detail'),
    path('<int:post_id>/comment/',add_comment, name='add_comment'),
    path('search/', search_blog_posts, name='search_blog_posts'),
    path('categories/', filter_categories, name='filter_categories'),
    path('tags/', filter_tags, name='filter_tags'),
    # Other URL patterns...

    #Left with Profile ... and Search and Filteration
]

BloggingPlatform/blogs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin


from django.contrib.auth.models import BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
    
        user.set_password(password)  #Create hashed password
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        # Generate a username based on the email
        username = email.split('@')[0]

        return self.create_user(email, password, username=username, **extra_fields)

class User(AbstractUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30,unique=False)
    last_name = models.CharField(max_length=30,unique=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return self.email
    


User = get_user_model()
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class BlogPost(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    body = models.TextField()
    categories = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(User, on_delete=models.CASCADE) #this needs to be fixed
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #version = models.IntegerField(default=1)

    def __str__(self): 
        return self.title

class Comment(models.Model):
    user_name = models.CharField(max_length=255)
    email = models.EmailField()
    comment_text = models.TextField()
    blog_post = models.ForeignKey('BlogPost', on_delete=models.CASCADE)
    #parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_text[:50]
    
from django.conf import settings

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    firstname = models.TextField()
    lastname=models.TextField()
    
    # Add any other fields you need for the user profile

    def __str__(self):
        return self.user.username

    

BloggingPlatform/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Blogging Platform</title>

</head>
<body>
    <!--NavBar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="{% url 'home' %}"><strong>Blogging Platform</strong></a>
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'search_blog_posts' %}">
            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

      {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {{break}}
      {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content%}
    <!--Footer-->
    <div class="container center" style="position:relative; top:auto;">
        <footer class="py-3 my-4">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
          </ul>
          <p class="text-center text-muted">© 2023 Company, Inc</p>
        </footer>
      </div>
    <script src="{% static 'css/bootstrap.js' %}"></script>
</body>
</html>

BloggingPlatform/templates/comment.html
{% block content %}
<!-- add_comment.html -->

<h2>Add a Comment</h2>

<form method="post" action=" ">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" style="margin-left:10%">Submit</button>
</form>
{% endblock content %}

BloggingPlatform/templates/edit_blog_post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card" style="margin:5%; margin-top:10px;">
  
    <div class="card-body">
      <h3 class="card-title">Edit the Blog Post</h3>
    <form method="post" action="">
      {% csrf_token %}
      <div class="form-group">
      <label for="id_title">Title</label>
      <input type="text" class="form-control" value="{{post.title}}" name="title" id="id_title" required>
      </div>
      <div class="form-group">
      <label for="id_description">Description</label>
      <textarea name="description" class="form-control" id="id_description" required>{{post.description}}</textarea>
      </div>
      <div class="form-group">
      <label for="id_body">Body</label>
      <textarea name="body" class="form-control"  id="id_body" required>{{post.body}}</textarea>
      </div>
      <button type="submit">Save Post</button>
    </form>
  </div>
  
  <p><a href="{% url 'add_comment' post.id %}"><i><b>Add Comment</b></i> <i class="fa fa-comment fa-lg"></i></a></p>
  </div>
{% endblock content %}

BloggingPlatform/templates/filter_categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if categories %}
<h2>Filter by Categories</h2>

<ul>
  {% for category in categories %}
    <li><a href="{% url 'search_blog_posts' %}?category={{ category.id }}">{{ category.name }}</a></li>
  {% endfor %}
</ul> 
{% endblock content %}

{% endif %}
<!-- filter_tags.html -->
{% if tags %}
<h2>Filter by Tags</h2>

<ul>
  {% for tag in tags %}
    <li><a href="{% url 'search_blog_posts' %}?tag={{ tag.id }}">{{ tag.name }}</a></li>
  {% endfor %}
</ul>
{% endif %}

BloggingPlatform/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- homepage.html -->

<div class="card center">
  <div class="card-body">
    <center>
<h2>Welcome to the Blogging Platform!</h2>
</center>
{% if user.is_authenticated %}
  <center><p>Hello, {{ user.first_name }} {{ user.last_name }}!  <a href="{{ 'profile/' }}">View Profile</a></p>
  
  <a href="{{ 'logout/' }}">Logout</a>
</center>
  <div class="card" style="margin:5%; margin-top:10px;">
  
  <div class="card-body">
    <h3 class="card-title">Create a New Blog Post</h3>
  <form method="post" action="{{ 'create-post/' }}">
    {% csrf_token %}
    <div class="form-group">
    <label for="id_title">Title</label>
    <input type="text" class="form-control" name="title" id="id_title" required>
    </div>
    <div class="form-group">
    <label for="id_description">Description</label>
    <textarea name="description" class="form-control" id="id_description" required></textarea>
    </div>
    <div class="form-group">
    <label for="id_body">Body</label>
    <textarea name="body" class="form-control" id="id_body" required></textarea>
    </div>
    <button type="submit">Create Post</button>
  </form>
</div>
</div>
  <hr>
{% else %}
  <center><p>Welcome to the Blogging Platform! Please <a href="{{ 'login/' }}">Login</a> or <a href="{{'register/' }}">Register</a> to start creating blog posts.</p>
{% endif %}
<hr>
<h3>Latest Blog Posts</h3>
<div class="row">
{% for post in posts %}
  <div class="column">
    <h4>{{ post.title }}</h4>
    <p>{{ post.description }}</p>
    <p>Author: {{ post.author.get_full_name }}</p>
    <p>Published: {{ post.created_at }}</p>
    <a href="{% url 'post_detail' post.id %}">Read More</a>
    <a href="{% url 'add_comment' post.id %}"><p><i><b>Add Comment</b></i> <i class="fa fa-comment fa-lg"></i></p></a>
  </div>
  <hr>
  
{% empty %}
  <p>No blog posts found.</p>
{% endfor %}
</div>
</div>
</div>
</center>

{% endblock content %}

BloggingPlatform/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>User Profile</h2>
<p>First Name: {{ user_profile.user.first_name }}</p>
<p>Last Name: {{ user_profile.user.last_name }}</p>
<p>Email: {{ user_profile.user.email }}</p>
<hr>
<h3>Your Blog Posts</h3>
<div class="row card" style="margin: 10%; margin-top:2%;">
{% for post in blog_posts %}
  <div class="column card-body">
    <h4>{{ post.title }}</h4>
    <p>{{ post.description }}</p>
    <p>Author: {{ post.author.get_full_name }}</p>
    <p>Published: {{ post.created_at }}</p>
    <a href="{% url 'post_detail' post.id %}">Read More</a>
    <a href="{% url 'add_comment' post.id %}"><p><i><b>Add Comment</b></i> <i class="fa fa-comment fa-lg"></i></p></a>
  </div>
  <hr>
  
{% empty %}
  <p>No blog posts found.</p>
{% endfor %}
</div>
{% endblock content %}

BloggingPlatform/templates/search_blog_posts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% for blog_post in blog_posts %}
  <h3>{{ blog_post.title }}</h3>
  <p>{{ blog_post.description }}</p>
  <p>{{blog_post.body}}</p>
  <!-- Display other blog post details -->
{% empty %}
  <p>No blog posts found.</p>
{% endfor %}
{% endblock content %}

BloggingPlatform/templates/viewpost.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card">
    <center>
    <h1 class="card-title">{{post.title}}</h1>
    <small>{{post.description}}</small></center>
    <div class="card-body">
        <p>{{post.body}}</p>
    </div>
    <h3>Comments</h3>
    {% for comment in comments %}
    <p>{{comment.comment_text}}</p>
    {% empty %}
    <p>No Comments Yet</p>
    {% endfor %}
</div>
<span class="d-flex "><a href = "{% url 'edit_blog_post' post.id %}"><p>Edit Post</p></a> <a style ='margin-left:90%' href = "{% url 'delete_blog_post' post.id %}"><p>Delete Post</p></a></span>
<p><a href="{% url 'add_comment' post.id %}"><i><b>Add Comment</b></i> <i class="fa fa-comment fa-lg"></i></a></p>

{% endblock content %}